apiVersion: v2
appVersion: "v2.222.1"
description: A Helm chart for deploying Jenkins on OpenShift with some additional build agents and plugins
name: jenkins
version: master
home: https://github.com/kborup-redhat/helm-charts
maintainers:
  - name: springdo
  - name: ckavili
  - name: eformat
