apiVersion: v2
appVersion: v1.5.4
description: A Helm chart for customising the deployment of the ArgoCD Operator ⚓️
name: argocd-operator
version: 0.0.10
home: https://github.com/kborup-redhat/helm-charts
maintainers:
- name: springdo
- name: ckavili
- name: eformat
